# Generated by Django 2.2.6 on 2019-10-29 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keebs', '0002_build_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='build',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
